### ISSUE TITLE
Getting Unrecognized field "guid" (Class org.springframework.social.alfresco.api.entities.Site)

### ISSUE THREAD

**Issue by jlcampos** [Alfresco/spring-social-alfresco#4]
Hi, im getting Unrecognized field "guid" (Class org.springframework.social.alfresco.api.entities.Site) im using version 0.2.8. After succesfully authenticated im invoking method getSites and im getting this error. 

Any help will be highly appreciated.

**Comment by jottley** [comment]
Let me look and see if the response format has changed.

**Comment by jottley** [comment]
I've taken a look at the code and I'm not able to reproduce it.  As part of the testing I also updated some of the dependencies and add some of the new missing activityTypes so that the unit tests would run and pass.  Can you retry with the 0.3.0 artifacts?

**Comment by jlcampos** [comment]
Hi, 

I was using https://github.com/pmonks/alfresco-cloud-sample-grails, I tried with my own Spring application and it is working. 

Best regards
